import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { buildGraph, Confidence, revitify } from "../src/index.js";

/**
 * Phase 1b behavior: confidence tagging + import resolution against the walked-file set.
 * Ports the spirit of graphify's symbol_resolution.py (EXTRACTED/INFERRED/AMBIGUOUS) at the
 * granularity revitify has today (file-level references; symbol-level lands in Phase 3).
 */

function project(files: Record<string, string>): string {
  const dir = mkdtempSync(join(tmpdir(), "revitify-resolve-"));
  for (const [rel, content] of Object.entries(files)) {
    mkdirSync(join(dir, rel.includes("/") ? rel.slice(0, rel.lastIndexOf("/")) : "."), {
      recursive: true,
    });
    writeFileSync(join(dir, rel), content);
  }
  return dir;
}

describe("confidence tagging", () => {
  const graph = buildGraph(
    project({
      "src/auth.ts": `import { hash } from "./crypto.js";\nexport function login(): void {}`,
      "src/crypto.ts": "export function hash(s: string): string { return s; }",
      "README.md": "# App\n",
    }),
  );

  it("structural contains/imports edges are EXTRACTED", () => {
    for (const relation of ["contains", "imports"]) {
      const links = graph.links.filter((l) => l.relation === relation);
      expect(links.length, `no ${relation} links`).toBeGreaterThan(0);
      for (const l of links) expect(l.confidence).toBe(Confidence.EXTRACTED);
    }
  });

  it("a uniquely-resolved reference is INFERRED", () => {
    const ref = graph.links.find((l) => l.relation === "references");
    expect(ref?.target).toBe("sym:src/crypto.ts#hash");
    expect(ref?.confidence).toBe(Confidence.INFERRED);
  });
});

describe("ambiguous references", () => {
  const files = {
    "a/util.ts": "export function helper(): void {}",
    "b/util.ts": "export function helper(): void {}",
    "b/caller.ts": `import { helper } from "../a/util.js";\nexport function run(): void {}`,
  };

  it("multiple candidates → AMBIGUOUS, picked deterministically with same-dir preference", () => {
    const graph = buildGraph(project(files));
    const ref = graph.links.find((l) => l.relation === "references");
    expect(ref?.confidence).toBe(Confidence.AMBIGUOUS);
    // caller.ts lives in b/ — the same-dir candidate wins over the lexicographically-first a/.
    expect(ref?.target).toBe("sym:b/util.ts#helper");
  });

  it("the pick is stable across runs", () => {
    const one = buildGraph(project(files)).links.find((l) => l.relation === "references");
    const two = buildGraph(project(files)).links.find((l) => l.relation === "references");
    expect(one?.target).toBe(two?.target);
  });
});

describe("import resolution against the walked-file set", () => {
  it("drops imports of files that do not exist; keeps ext-swapped, as-written, and index targets", () => {
    const graph = buildGraph(
      project({
        "src/main.ts": [
          `import { hash } from "./crypto.js";`, // .js → .ts swap
          `import real from "./real.js";`, // real .js file, as written
          `import { u } from "./utils";`, // directory → utils/index.ts
          `import gone from "./missing.js";`, // nothing on disk — dropped
        ].join("\n"),
        "src/crypto.ts": "export function hash(s: string): string { return s; }",
        "src/real.js": "export default 1;",
        "src/utils/index.ts": "export const u = 1;",
      }),
    );
    const targets = graph.links.filter((l) => l.relation === "imports").map((l) => l.target);
    expect(targets).toContain("file:src/crypto.ts");
    expect(targets).toContain("file:src/real.js");
    expect(targets).toContain("file:src/utils/index.ts");
    expect(targets.some((t) => String(t).includes("missing"))).toBe(false);
  });
});

describe("self-output exclusion", () => {
  it("a previous revitify-out/ run is never ingested back into the graph", () => {
    const dir = project({
      "src/a.ts": "export const a = 1;",
      "revitify-out/GRAPH_REPORT.md": "# Graph report — generated by revitify\n## Node kinds\n",
    });
    const labels = revitify(dir) && buildGraph(dir).nodes.map((n) => n.label);
    expect(labels.some((l) => l.includes("Graph report"))).toBe(false);
    expect(labels.some((l) => l.includes("Node kinds"))).toBe(false);
  });
});

describe("ambiguity without a same-dir candidate", () => {
  it("falls back to lexicographic id order, still AMBIGUOUS", () => {
    const graph = buildGraph(
      project({
        "zeta/util.ts": "export function helper(): void {}",
        "alpha/util.ts": "export function helper(): void {}",
        "mid/caller.ts": `import { helper } from "../alpha/util.js";\nexport function run(): void {}`,
      }),
    );
    const ref = graph.links.find((l) => l.relation === "references");
    expect(ref?.confidence).toBe(Confidence.AMBIGUOUS);
    expect(ref?.target).toBe("sym:alpha/util.ts#helper"); // lexicographically first
  });
});
