import { kindCounts, topHubs } from "../enrich/report-data.js";
import type { RevitifyGraph } from "../model/graph.js";
import type { Exporter } from "./exporter.js";

export function renderReport(graph: RevitifyGraph): string {
  const hubs = topHubs(graph);
  const kinds = kindCounts(graph);

  return [
    "# Graph report — generated by revitify",
    "",
    `**${graph.nodes.length} nodes · ${graph.links.length} links**${
      graph.built_at_commit ? ` · built at \`${graph.built_at_commit.slice(0, 8)}\`` : ""
    }`,
    "",
    "## Node kinds",
    "",
    ...[...kinds.entries()].sort((a, b) => b[1] - a[1]).map(([k, c]) => `- ${k}: ${c}`),
    "",
    "## Most connected (the load-bearing walls)",
    "",
    ...hubs.map((h) => `- **${h.node.label}** (${h.degree} edges) — \`${h.node.source_file}\``),
    "",
    "## Suggested questions",
    "",
    ...hubs
      .slice(0, 3)
      .map((h) => `- What breaks if \`${h.node.label}\` changes? (rivet affected ${h.node.label})`),
    "- Which files have symbols nothing references (dead weight)?",
    "- Open graph.html and search a requirement's area — does the code shape match the spec shape?",
    "",
  ].join("\n");
}

export const reportExporter: Exporter = {
  id: "report",
  filename: "GRAPH_REPORT.md",
  render: (graph) => renderReport(graph),
};
