import { godNodes } from "../enrich/god-nodes.js";
import { confidenceSummary, suggestedQuestions } from "../enrich/questions.js";
import { kindCounts } from "../enrich/report-data.js";
import { surprisingConnections } from "../enrich/surprise.js";
import type { RevitifyGraph } from "../model/graph.js";
import { GraphIndex } from "../query/graph.js";
import type { Exporter } from "./exporter.js";

/** GRAPH_REPORT.md — graphify report.py's sections at revitify's depth. */
export function renderReport(graph: RevitifyGraph): string {
  // One adjacency index, shared across god-nodes / surprise / questions (each else rebuilds it).
  const index = new GraphIndex(graph);
  const gods = godNodes(graph, 10, index);
  const kinds = kindCounts(graph);
  const surprises = surprisingConnections(graph, 5, index);
  const confidence = confidenceSummary(graph);
  const why = graph.nodes.filter((n) => n.kind === "why" || n.kind === "docstring");
  const byId = new Map(graph.nodes.map((n) => [n.id, n]));
  const communities = new Set(graph.nodes.map((n) => n.community).filter((c) => c !== undefined))
    .size;

  const lines = [
    "# Graph report — generated by revitify",
    "",
    `**${graph.nodes.length} nodes · ${graph.links.length} links · ${communities} communities**${
      graph.built_at_commit ? ` · built at \`${graph.built_at_commit.slice(0, 8)}\`` : ""
    }`,
    "",
    "## Node kinds",
    "",
    ...[...kinds.entries()].sort((a, b) => b[1] - a[1]).map(([k, c]) => `- ${k}: ${c}`),
    "",
    "## God nodes (most connected symbols)",
    "",
    ...(gods.length
      ? gods.map(
          (g) =>
            `- **${g.node.label}** (${g.degree} edges, ${g.node.kind}) — \`${g.node.source_file}\``,
        )
      : ["- none — no connected symbols yet"]),
    "",
    "## Surprising connections",
    "",
    ...(surprises.length
      ? surprises.map((s) => {
          const from = byId.get(String(s.link.source));
          const to = byId.get(String(s.link.target));
          return `- **${from?.label}** ${s.link.relation} **${to?.label}** (score ${s.score}: ${s.reasons.join(", ")})`;
        })
      : ["- none above threshold — the graph holds few cross-cutting secrets"]),
    "",
    "## Confidence",
    "",
    ...confidence.map(([c, n, pct]) => `- ${c}: ${n} (${pct}%)`),
  ];

  if (why.length) {
    lines.push(
      "",
      `## Why-nodes (${why.length})`,
      "",
      ...why.slice(0, 10).map((n) => `- \`${n.source_file}\` — ${n.label}`),
    );
  }

  lines.push(
    "",
    "## Suggested questions",
    "",
    ...suggestedQuestions(graph, 5, index).map((q) => `- ${q}`),
    "",
  );
  return lines.join("\n");
}

export const reportExporter: Exporter = {
  id: "report",
  filename: "GRAPH_REPORT.md",
  render: (graph) => renderReport(graph),
};
