import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { ingest } from "./ingest.js";
import { renderHtml } from "./html.js";
import type { RevitifyGraph } from "./types.js";

export type { RevitifyGraph, RevitifyNode, RevitifyLink } from "./types.js";
export { walkFiles } from "./ingest.js";

/**
 * Revitify — Rivet's native TypeScript counterpart to graphify (concepts adapted from
 * github.com/safishamsi/graphify, MIT; original implementation). Turns a folder of code + docs
 * into a queryable knowledge graph with graphify's exact output contract:
 *   graphify-out/graph.json · graph.html · GRAPH_REPORT.md
 * v1 scope = what Rivet needs: TS/JS (compiler API), Python/Java (best-effort), markdown.
 * Multi-modal ingestion (PDF/images/video) and Leiden clustering remain graphify's depth.
 */

export function buildGraph(rootDir: string): RevitifyGraph {
  const { nodes, links } = ingest(rootDir);
  const head = gitHead(rootDir);
  return { nodes, links, ...(head ? { built_at_commit: head } : {}) };
}

export function renderReport(graph: RevitifyGraph): string {
  const degree = new Map<string, number>();
  for (const l of graph.links) {
    degree.set(String(l.source), (degree.get(String(l.source)) ?? 0) + 1);
    degree.set(String(l.target), (degree.get(String(l.target)) ?? 0) + 1);
  }
  const byId = new Map(graph.nodes.map((n) => [n.id, n]));
  const hubs = [...degree.entries()]
    .map(([id, d]) => ({ node: byId.get(id), d }))
    .filter((h) => h.node)
    .sort((a, b) => b.d - a.d)
    .slice(0, 10);
  const kinds = new Map<string, number>();
  for (const n of graph.nodes) kinds.set(n.kind ?? "node", (kinds.get(n.kind ?? "node") ?? 0) + 1);

  return [
    "# Graph report — generated by revitify",
    "",
    `**${graph.nodes.length} nodes · ${graph.links.length} links**` +
      (graph.built_at_commit ? ` · built at \`${graph.built_at_commit.slice(0, 8)}\`` : ""),
    "",
    "## Node kinds",
    "",
    ...[...kinds.entries()].sort((a, b) => b[1] - a[1]).map(([k, c]) => `- ${k}: ${c}`),
    "",
    "## Most connected (the load-bearing walls)",
    "",
    ...hubs.map((h) => `- **${h.node!.label}** (${h.d} edges) — \`${h.node!.source_file}\``),
    "",
    "## Suggested questions",
    "",
    ...hubs
      .slice(0, 3)
      .map((h) => `- What breaks if \`${h.node!.label}\` changes? (rivet affected ${h.node!.label})`),
    "- Which files have symbols nothing references (dead weight)?",
    "- Open graph.html and search a requirement's area — does the code shape match the spec shape?",
    "",
  ].join("\n");
}

export interface RevitifyResult {
  graphJsonPath: string;
  counts: { nodes: number; links: number };
}

/** The one-call entrypoint: ingest → emit the full graphify-out/ contract. */
export function revitify(rootDir: string, outDir = "graphify-out"): RevitifyResult {
  const graph = buildGraph(rootDir);
  const out = join(rootDir, outDir);
  mkdirSync(out, { recursive: true });
  const graphJsonPath = join(out, "graph.json");
  writeFileSync(graphJsonPath, JSON.stringify(graph, null, 2) + "\n");
  writeFileSync(join(out, "graph.html"), renderHtml(graph));
  writeFileSync(join(out, "GRAPH_REPORT.md"), renderReport(graph));
  return { graphJsonPath, counts: { nodes: graph.nodes.length, links: graph.links.length } };
}

function gitHead(cwd: string): string | undefined {
  const res = spawnSync("git", ["rev-parse", "HEAD"], { cwd, stdio: ["ignore", "pipe", "ignore"] });
  return res.status === 0 ? res.stdout.toString().trim() : undefined;
}
